#!/bin/bash

echo "================ Syncronizing ================"

cd ~/svxlink
git pull origin

echo "================ Building ================"

mkdir ~/svxlink/src/build
cd ~/svxlink/src/build
cmake -DUSE_QT=OFF -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DWITH_SYSTEMD=ON ..
make -j4
make doc
make man
make async-doc

echo "================ Installing ================"

sudo make install

echo "================ Caching libraries ================"

sudo ldconfig

echo "================ Installing sound files ================"

sudo wget -c https://github.com/sm0svx/svxlink-sounds-sv_SE-elin/releases/download/19.09.99.1/svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2 \
-O /usr/share/svxlink/sounds/svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2
sudo wget -c https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/19.09.99.1/svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2 \
-O /usr/share/svxlink/sounds/svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2
cd /usr/share/svxlink/sounds/
sudo tar xvjf svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2
sudo tar xvjf svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2

echo "================ Finished ================"
