#!/bin/bash

echo "================ Installing dependencies ================"

sudo apt update
sudo apt install -y  g++ cmake make libsigc++-2.0-dev libgsm1-dev libpopt-dev tcl-dev libgcrypt20-dev libspeex-dev libasound2-dev libopus-dev librtlsdr-dev \
doxygen groff alsa-utils vorbis-tools curl libcurl4-openssl-dev git rtl-sdr libcurl4-openssl-dev libjsoncpp-dev libgpiod-dev gpiod \
g++ cmake make build-essential libsigc++-2.0-dev libgsm1-dev libpopt-dev tcl8.6-dev libgcrypt20-dev libspeex-dev libasound2-dev \
libopus-dev librtlsdr-dev doxygen vorbis-tools curl libcurl4-openssl-dev git rtl-sdr libcurl4-openssl-dev cmake libjsoncpp-dev libusb-1.0-doc \
libasyncaudio-dev libasynccore-dev libasyncqt-dev libecholib-dev libaudio2 libpulse0 libsndio7.0  lrzip libasound2-doc libcurl4-doc libidn11-dev \
libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libgcrypt20-doc opus-tools libthai0 qt5-image-formats-plugins qtwayland5 libsigc++-2.0-doc speex \
tcl8.6-doc cmake-doc ninja-build doxygen-latex doxygen-doc graphviz libsndio-dev libasynccpp1.6 libasynccpp-dev libtcl8.6 \
libogg-dev libogg0 groff libsigc++-2.0-dev libspeex-dev libopus-dev doxygen psutils \
ghostscript imagemagick libpaper1 netpbm psutils libusb-1.0-doc

echo "================ Creating groups and users ================"

sudo useradd -U -r -G audio,plugdev,daemon,gpio,dialout -c 'Svxlink-related Daemons' -d /tmp -M -s /usr/bin/false svxlink

echo "================ Cloning repositories ================"

cd ~
git clone https://github.com/sm0svx/svxlink.git

echo "================ Creating build folders ================"
mkdir ~/svxlink/src/build
cd ~/svxlink/src/build

echo "================ Building ================"

cmake -DUSE_QT=OFF -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DWITH_SYSTEMD=ON ..
make -j4
make doc
make man
make async-doc

echo "================ Installing ================"

sudo make install

echo "================ Caching libraries ================"

sudo ldconfig

echo "================ Installing sound files ================"

sudo wget -c https://github.com/sm0svx/svxlink-sounds-sv_SE-elin/releases/download/19.09.99.1/svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2 \
-O /usr/share/svxlink/sounds/svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2
sudo wget -c https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/19.09.99.1/svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2 \
-O /usr/share/svxlink/sounds/svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2
cd /usr/share/svxlink/sounds/
sudo tar xvjf svxlink-sounds-sv_SE-elin-16k-19.09.99.1.tar.bz2
sudo tar xvjf svxlink-sounds-en_US-heather-16k-19.09.99.1.tar.bz2

echo "================ Finished ================"
